# Generated by Django 5.1.2 on 2025-08-14 20:17

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0004_add_dual_logos"),
        ("units", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="unit",
        ),
        migrations.AddField(
            model_name="user",
            name="units",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="units.unit",
                verbose_name="Unidades",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="enterprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="enterprises.enterprise",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Ativo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Django Staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, null=True, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.user_directory_path,
                verbose_name="Imagem de Perfil",
            ),
        ),
    ]
