# Generated by Django 5.1.2 on 2025-08-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_unit_user_units_alter_user_cpf_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("manage_banks_master", "Gerenciar bancos (nível master)"),
                    (
                        "manage_credit_lines_master",
                        "Gerenciar linhas de crédito (nível master)",
                    ),
                    ("manage_units_master", "Gerenciar unidades (nível master)"),
                    ("add_unit_messages", "Adicionar mensagens para unidade"),
                    ("add_company_messages", "Adicionar mensagens para toda empresa"),
                ]
            },
        ),
    ]
