# Generated by Django 5.2.5 on 2025-09-03 23:14

import django.db.models.deletion
import django.utils.timezone
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=projects.models.project_document_directory_path,
                        verbose_name="Documento",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="Tipo de Arquivo"),
                ),
                (
                    "file_size",
                    models.IntegerField(verbose_name="Tamanho do Arquivo (bytes)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(verbose_name="Alterações")),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to="enterprises.enterprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CreditLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type_credit",
                    models.CharField(
                        choices=[
                            ("CUS", "Custeio"),
                            ("INV", "Investimento"),
                            ("OTH", "Outros"),
                        ],
                        default="CUS",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_lines",
                        to="enterprises.enterprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Crédito",
                "verbose_name_plural": "Linhas de Crédito",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AC", "Em Acolhimento"),
                            ("PE", "Com Pendência"),
                            ("AN", "Em Análise"),
                            ("AP", "Aprovados"),
                            ("AF", "Em Formalização"),
                            ("FM", "Formalizado"),
                            ("LB", "Liberado"),
                            ("RC", "Receita"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                (
                    "land_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Tamanho da Terra (ha)",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[("PQ", "Pequeno"), ("MD", "Médio"), ("GD", "Grande")],
                        max_length=2,
                        verbose_name="Tamanho do Projeto",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AGR", "Agricultura"),
                            ("PEC", "Pecuária"),
                            ("OUT", "Outros"),
                        ],
                        max_length=3,
                        verbose_name="Atividade",
                    ),
                ),
                (
                    "documents_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição de Documentos"
                    ),
                ),
                (
                    "next_phase_deadline",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Prazo Estimado Próxima Fase",
                    ),
                ),
                (
                    "installments",
                    models.IntegerField(blank=True, null=True, verbose_name="Parcelas"),
                ),
                (
                    "fees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Juros",
                    ),
                ),
                (
                    "payment_grace",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Carência para pagamento"
                    ),
                ),
                (
                    "project_deadline",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prazo para pagamento do Projeto",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do Projeto",
                    ),
                ),
                (
                    "percentage_astec",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Porcentagem ASTEC",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Aprovação"
                    ),
                ),
                (
                    "consortium_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Valor do Consórcio",
                    ),
                ),
                (
                    "project_finalized",
                    models.BooleanField(
                        default=False, verbose_name="Projeto Finalizado"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.bank",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="enterprises.client",
                    ),
                ),
                (
                    "credit_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.creditline",
                    ),
                ),
                (
                    "enterprise",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="enterprises.enterprise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-created_at"],
            },
        ),
    ]
