# Generated by Django 5.2.6 on 2025-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="first_installment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Primeira Parcela"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="last_installment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Última Parcela"
            ),
        ),
        migrations.AlterField(
            model_name="creditline",
            name="type_credit",
            field=models.CharField(
                choices=[
                    ("CUS", "Custeio"),
                    ("INV", "Investimento"),
                    ("PRO", "Prorrogação"),
                    ("CPR", "CPR"),
                    ("OTH", "Outros"),
                ],
                default="CUS",
                max_length=3,
            ),
        ),
    ]
