# Generated by Django 5.2.6 on 2025-09-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_first_installment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="received_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor Recebido",
            ),
        ),
    ]
