# Generated by Django 5.2.5 on 2025-09-10 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "royalties_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de Royalties (%)",
                    ),
                ),
                (
                    "marketing_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de Marketing (%)",
                    ),
                ),
                (
                    "designers_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de Projetistas (%)",
                    ),
                ),
                (
                    "collectors_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Porcentagem de Captadores (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Unidade",
                "verbose_name_plural": "Unidades",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da Conta"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=255, verbose_name="Nome do Banco"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Conta Poupança"),
                            ("INVESTIMENTO", "Conta de Investimento"),
                            ("OUTROS", "Outros"),
                        ],
                        default="CORRENTE",
                        max_length=15,
                        verbose_name="Tipo de Conta",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número da Conta",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Agência"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Saldo Inicial",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="enterprises.enterprise",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
                "ordering": ["bank_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RECEITA", "Receita"),
                            ("COMISSAO", "Comissão"),
                            ("BONUS", "Bônus"),
                            ("REEMBOLSO", "Reembolso"),
                            ("MATERIAL", "Material de Escritório"),
                            ("TRANSPORTE", "Transporte"),
                            ("ALIMENTACAO", "Alimentação"),
                            ("COMBUSTIVEL", "Combustível"),
                            ("MANUTENCAO", "Manutenção"),
                            ("MARKETING", "Marketing"),
                            ("TREINAMENTO", "Treinamento"),
                            ("SALARIO", "Salário"),
                            ("SALARIO_TOTAL", "Salário Total"),
                            ("RECEITA_CREDITO_RURAL", "Receita Crédito Rural"),
                            ("RECEITA_CONSORCIO", "Receita Consórcio"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=25,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="units.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
