# Generated by Django 5.2.5 on 2025-09-10 22:23

import enterprises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="CPF do cliente (formato: XXX.XXX.XXX-XX)",
                        max_length=14,
                        null=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="City"
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observations"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "producer_classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEQUENO", "Pequeno Produtor"),
                            ("MEDIO", "Médio Produtor"),
                            ("GRANDE", "Grande Produtor"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Enquadramento do Produtor",
                    ),
                ),
                (
                    "property_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Área total do produtor em hectares",
                        max_digits=10,
                        null=True,
                        verbose_name="Área Total do Produtor (hectares)",
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AGRICULTURA", "Agricultura"),
                            ("PECUARIA", "Pecuária"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Atividade Principal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INATIVO", "Inativo"),
                            ("INTERESSADO", "Interessado"),
                            ("EM_NEGOCIACAO", "Negociação"),
                            ("ATIVO", "Ativo"),
                        ],
                        default="INATIVO",
                        max_length=15,
                        verbose_name="Situação",
                    ),
                ),
                (
                    "retorno_ate",
                    models.DateField(
                        blank=True,
                        help_text="Data de retorno obrigatória quando em negociação",
                        null=True,
                        verbose_name="Retorno até",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        help_text="Número da agência (ex: 1234)",
                        max_length=10,
                        verbose_name="Agência",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Número da conta com dígito (ex: 12345-6)",
                        max_length=20,
                        verbose_name="Número da Conta",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Poupança"),
                            ("SALARIO", "Conta Salário"),
                        ],
                        default="CORRENTE",
                        max_length=20,
                        verbose_name="Tipo de Conta",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária do Cliente",
                "verbose_name_plural": "Contas Bancárias dos Clientes",
                "ordering": ["bank__name"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=enterprises.models.client_document_directory_path,
                        verbose_name="Document",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_type", models.CharField(max_length=100)),
                ("file_size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ClientHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("changes", models.JSONField(verbose_name="Alterações")),
            ],
            options={
                "verbose_name": "Histórico do Cliente",
                "verbose_name_plural": "Históricos dos Clientes",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cnpj_or_cpf", models.CharField(max_length=18)),
                (
                    "subdomain",
                    models.CharField(
                        help_text="Subdomínio único para acesso (ex: saldus.nexiun.com.br)",
                        max_length=63,
                        unique=True,
                        validators=[enterprises.models.validate_subdomain],
                        verbose_name="Subdomínio",
                    ),
                ),
                (
                    "logo_light",
                    models.ImageField(
                        blank=True,
                        default="icons/logo.svg",
                        help_text="Logo para usar em fundos claros",
                        null=True,
                        upload_to=enterprises.models.enterprise_directory_path,
                        verbose_name="Logo Claro",
                    ),
                ),
                (
                    "logo_dark",
                    models.ImageField(
                        blank=True,
                        default="icons/logo_white.svg",
                        help_text="Logo para usar em fundos escuros",
                        null=True,
                        upload_to=enterprises.models.enterprise_directory_path,
                        verbose_name="Logo Escuro",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        default="icons/favicon.svg",
                        help_text="Ícone que aparece na aba do navegador (formato .ico, .png ou .svg)",
                        null=True,
                        upload_to=enterprises.models.enterprise_directory_path,
                        verbose_name="Favicon",
                    ),
                ),
                ("primary_color", models.CharField(default="#05677D", max_length=7)),
                ("secondary_color", models.CharField(default="#FFB845", max_length=7)),
                ("text_icons_color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("content", models.TextField(verbose_name="Conteúdo")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expira em"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Aviso"),
                            ("danger", "Urgente"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Nível",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("empresa", "Toda a Empresa"),
                            ("unidade", "Unidade Específica"),
                        ],
                        default="empresa",
                        max_length=20,
                        verbose_name="Escopo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem Interna",
                "verbose_name_plural": "Mensagens Internas",
                "ordering": ["-date"],
            },
        ),
    ]
