# Generated by Django 5.2.5 on 2025-08-13 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0001_initial"),
        ("units", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_clients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cadastrado por",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="units",
            field=models.ManyToManyField(
                blank=True,
                related_name="clients",
                to="units.unit",
                verbose_name="Unidades",
            ),
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="enterprises.client",
            ),
        ),
        migrations.AddField(
            model_name="clienthistory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="enterprises.client",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="enterprises.enterprise",
                verbose_name="Enterprise",
            ),
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="enterprises.enterprise",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="units.unit",
                verbose_name="Unidade",
            ),
        ),
    ]
