# Generated by Django 5.1.2 on 2025-08-13 17:21

import enterprises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="logo",
            field=models.ImageField(
                blank=True,
                default="icons/logo_white.svg",
                null=True,
                upload_to=enterprises.models.enterprise_directory_path,
            ),
        ),
    ]
