# Generated by Django 5.1.2 on 2025-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURA", "Agricultura"),
                    ("PECUARIA", "Pecuária"),
                    ("AGRICULTURA/PECUARIA", "Agricultura/Pecuária"),
                    ("OUTROS", "Outros"),
                ],
                max_length=25,
                null=True,
                verbose_name="Atividade Principal",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
    ]
