# Generated by Django 5.1.2 on 2025-08-13 18:42

import enterprises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0003_update_default_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="logo",
        ),
        migrations.AddField(
            model_name="enterprise",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                default="icons/logo_white.svg",
                help_text="Logo para usar em fundos escuros",
                null=True,
                upload_to=enterprises.models.enterprise_directory_path,
                verbose_name="Logo Escuro",
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="logo_light",
            field=models.ImageField(
                blank=True,
                default="icons/logo.svg",
                help_text="Logo para usar em fundos claros",
                null=True,
                upload_to=enterprises.models.enterprise_directory_path,
                verbose_name="Logo Claro",
            ),
        ),
    ]
