# Generated by Django 5.1.2 on 2025-08-15 04:28

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0004_add_dual_logos"),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em', default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
