# Generated by Django 5.1.2 on 2025-08-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0005_auto_20250815_0428"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AGRICULTURA", "Agricultura"),
                    ("PECUARIA", "Pecuária"),
                    ("OUTROS", "Outros"),
                ],
                max_length=15,
                null=True,
                verbose_name="Atividade Principal",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="cpf",
            field=models.CharField(
                blank=True,
                help_text="CPF do cliente (formato: XXX.XXX.XXX-XX)",
                max_length=14,
                null=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="producer_classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PEQUENO", "Pequeno Produtor"),
                    ("MEDIO", "Médio Produtor"),
                    ("GRANDE", "Grande Produtor"),
                ],
                max_length=10,
                null=True,
                verbose_name="Enquadramento do Produtor",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="property_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Área total do imóvel em hectares",
                max_digits=10,
                null=True,
                verbose_name="Área Total do Imóvel (hectares)",
            ),
        ),
    ]
