# Generated by Django 5.1.2 on 2025-08-26 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0006_client_activity_client_cpf_and_more"),
        ("projects", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="property_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Área total do produtor em hectares",
                max_digits=10,
                null=True,
                verbose_name="Área Total do Produtor (hectares)",
            ),
        ),
        migrations.CreateModel(
            name="ClientBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agency",
                    models.CharField(
                        help_text="Número da agência (ex: 1234)",
                        max_length=10,
                        verbose_name="Agência",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Número da conta com dígito (ex: 12345-6)",
                        max_length=20,
                        verbose_name="Número da Conta",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Poupança"),
                            ("SALARIO", "Conta Salário"),
                        ],
                        default="CORRENTE",
                        max_length=20,
                        verbose_name="Tipo de Conta",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se esta é a conta principal do cliente",
                        verbose_name="Conta Principal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.bank",
                        verbose_name="Banco",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="enterprises.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_bank_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária do Cliente",
                "verbose_name_plural": "Contas Bancárias dos Clientes",
                "ordering": ["-is_primary", "bank__name"],
                "unique_together": {("client", "bank", "agency", "account_number")},
            },
        ),
    ]
