# Generated by Django 5.1.2 on 2025-09-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprises", "0007_alter_client_property_area_clientbankaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientbankaccount",
            options={
                "ordering": ["bank__name"],
                "verbose_name": "Conta Bancária do Cliente",
                "verbose_name_plural": "Contas Bancárias dos Clientes",
            },
        ),
        migrations.RemoveField(
            model_name="clientbankaccount",
            name="is_primary",
        ),
    ]
