# Generated by Django 5.1.2 on 2025-08-14 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("enterprises", "0004_add_dual_logos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_period_days",
                    models.IntegerField(
                        default=365, verbose_name="Período Padrão (dias)"
                    ),
                ),
                (
                    "auto_refresh_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Atualização Automática"
                    ),
                ),
                (
                    "auto_refresh_interval",
                    models.IntegerField(
                        default=60, verbose_name="Intervalo de Atualização (min)"
                    ),
                ),
                (
                    "email_reports_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Relatórios por Email"
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Frequência dos Emails",
                    ),
                ),
                (
                    "target_proposals_month",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Meta Propostas/Mês"
                    ),
                ),
                (
                    "target_approval_time_days",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Meta Tempo Aprovação (dias)",
                    ),
                ),
                (
                    "target_conversion_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Meta Taxa Conversão (%)",
                    ),
                ),
                (
                    "target_repurchase_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Meta Taxa Recompra (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Relatório",
                "verbose_name_plural": "Configurações de Relatórios",
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Relatório"),
                ),
                ("filters", models.JSONField(default=dict, verbose_name="Filtros")),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Diário"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensal"),
                        ],
                        max_length=20,
                        verbose_name="Frequência",
                    ),
                ),
                ("next_run", models.DateTimeField(verbose_name="Próxima Execução")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relatório Agendado",
                "verbose_name_plural": "Relatórios Agendados",
            },
        ),
        migrations.CreateModel(
            name="ReportCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(max_length=50, verbose_name="Tipo de Relatório"),
                ),
                (
                    "filter_hash",
                    models.CharField(max_length=64, verbose_name="Hash dos Filtros"),
                ),
                ("data", models.JSONField(verbose_name="Dados do Relatório")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enterprises.enterprise",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache de Relatório",
                "verbose_name_plural": "Cache de Relatórios",
                "unique_together": {("report_type", "filter_hash", "enterprise")},
            },
        ),
    ]
